// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: pkg/mensajero.proto

package pkg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Correcto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *Correcto) Reset() {
	*x = Correcto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_mensajero_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Correcto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Correcto) ProtoMessage() {}

func (x *Correcto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mensajero_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Correcto.ProtoReflect.Descriptor instead.
func (*Correcto) Descriptor() ([]byte, []int) {
	return file_pkg_mensajero_proto_rawDescGZIP(), []int{0}
}

func (x *Correcto) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ObtenerConLimite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Largo int32 `protobuf:"varint,1,opt,name=largo,proto3" json:"largo,omitempty"`
}

func (x *ObtenerConLimite) Reset() {
	*x = ObtenerConLimite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_mensajero_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObtenerConLimite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObtenerConLimite) ProtoMessage() {}

func (x *ObtenerConLimite) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mensajero_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObtenerConLimite.ProtoReflect.Descriptor instead.
func (*ObtenerConLimite) Descriptor() ([]byte, []int) {
	return file_pkg_mensajero_proto_rawDescGZIP(), []int{1}
}

func (x *ObtenerConLimite) GetLargo() int32 {
	if x != nil {
		return x.Largo
	}
	return 0
}

type ListaUsuarios struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Usuarios []string `protobuf:"bytes,1,rep,name=usuarios,proto3" json:"usuarios,omitempty"`
}

func (x *ListaUsuarios) Reset() {
	*x = ListaUsuarios{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_mensajero_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListaUsuarios) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaUsuarios) ProtoMessage() {}

func (x *ListaUsuarios) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mensajero_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaUsuarios.ProtoReflect.Descriptor instead.
func (*ListaUsuarios) Descriptor() ([]byte, []int) {
	return file_pkg_mensajero_proto_rawDescGZIP(), []int{2}
}

func (x *ListaUsuarios) GetUsuarios() []string {
	if x != nil {
		return x.Usuarios
	}
	return nil
}

type Registracion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UsuarioOrigen string `protobuf:"bytes,1,opt,name=usuarioOrigen,proto3" json:"usuarioOrigen,omitempty"`
}

func (x *Registracion) Reset() {
	*x = Registracion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_mensajero_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Registracion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registracion) ProtoMessage() {}

func (x *Registracion) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mensajero_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registracion.ProtoReflect.Descriptor instead.
func (*Registracion) Descriptor() ([]byte, []int) {
	return file_pkg_mensajero_proto_rawDescGZIP(), []int{3}
}

func (x *Registracion) GetUsuarioOrigen() string {
	if x != nil {
		return x.UsuarioOrigen
	}
	return ""
}

type TokenAutenticacion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *TokenAutenticacion) Reset() {
	*x = TokenAutenticacion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_mensajero_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenAutenticacion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenAutenticacion) ProtoMessage() {}

func (x *TokenAutenticacion) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mensajero_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenAutenticacion.ProtoReflect.Descriptor instead.
func (*TokenAutenticacion) Descriptor() ([]byte, []int) {
	return file_pkg_mensajero_proto_rawDescGZIP(), []int{4}
}

func (x *TokenAutenticacion) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Vacio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Vacio) Reset() {
	*x = Vacio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_mensajero_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vacio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vacio) ProtoMessage() {}

func (x *Vacio) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mensajero_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vacio.ProtoReflect.Descriptor instead.
func (*Vacio) Descriptor() ([]byte, []int) {
	return file_pkg_mensajero_proto_rawDescGZIP(), []int{5}
}

// TODO: Crear un mensaje denominado MensajeApp que contenga dos cadenas:
// `usuario` y `cuerpo`.
type MensajeApp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Usuario string `protobuf:"bytes,1,opt,name=usuario,proto3" json:"usuario,omitempty"`
	Cuerpo  string `protobuf:"bytes,2,opt,name=cuerpo,proto3" json:"cuerpo,omitempty"`
}

func (x *MensajeApp) Reset() {
	*x = MensajeApp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_mensajero_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MensajeApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MensajeApp) ProtoMessage() {}

func (x *MensajeApp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mensajero_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MensajeApp.ProtoReflect.Descriptor instead.
func (*MensajeApp) Descriptor() ([]byte, []int) {
	return file_pkg_mensajero_proto_rawDescGZIP(), []int{6}
}

func (x *MensajeApp) GetUsuario() string {
	if x != nil {
		return x.Usuario
	}
	return ""
}

func (x *MensajeApp) GetCuerpo() string {
	if x != nil {
		return x.Cuerpo
	}
	return ""
}

// TODO: Crear un mensaje denominado MensajesApp que contenga una lista repetida
// de MensajeApp
type MensajesApp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mensajes []*MensajeApp `protobuf:"bytes,1,rep,name=mensajes,proto3" json:"mensajes,omitempty"`
}

func (x *MensajesApp) Reset() {
	*x = MensajesApp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_mensajero_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MensajesApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MensajesApp) ProtoMessage() {}

func (x *MensajesApp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mensajero_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MensajesApp.ProtoReflect.Descriptor instead.
func (*MensajesApp) Descriptor() ([]byte, []int) {
	return file_pkg_mensajero_proto_rawDescGZIP(), []int{7}
}

func (x *MensajesApp) GetMensajes() []*MensajeApp {
	if x != nil {
		return x.Mensajes
	}
	return nil
}

var File_pkg_mensajero_proto protoreflect.FileDescriptor

var file_pkg_mensajero_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x72, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x72, 0x6f,
	0x22, 0x1a, 0x0a, 0x08, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02,
	0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x28, 0x0a, 0x10,
	0x4f, 0x62, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x72, 0x67, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x6c, 0x61, 0x72, 0x67, 0x6f, 0x22, 0x2b, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x55,
	0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x75, 0x61, 0x72,
	0x69, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x75, 0x61, 0x72,
	0x69, 0x6f, 0x73, 0x22, 0x34, 0x0a, 0x0c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x63,
	0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x4f, 0x72,
	0x69, 0x67, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x75, 0x73, 0x75, 0x61,
	0x72, 0x69, 0x6f, 0x4f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x22, 0x2a, 0x0a, 0x12, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x41, 0x75, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x07, 0x0a, 0x05, 0x56, 0x61, 0x63, 0x69, 0x6f, 0x22, 0x3e,
	0x0a, 0x0a, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x41, 0x70, 0x70, 0x12, 0x18, 0x0a, 0x07,
	0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75,
	0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x75, 0x65, 0x72, 0x70, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x75, 0x65, 0x72, 0x70, 0x6f, 0x22, 0x40,
	0x0a, 0x0b, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x73, 0x41, 0x70, 0x70, 0x12, 0x31, 0x0a,
	0x08, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x72, 0x6f, 0x2e, 0x4d, 0x65, 0x6e, 0x73,
	0x61, 0x6a, 0x65, 0x41, 0x70, 0x70, 0x52, 0x08, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x73,
	0x32, 0xa6, 0x02, 0x0a, 0x09, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x72, 0x6f, 0x12, 0x42,
	0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x65, 0x63, 0x74, 0x61, 0x72, 0x12, 0x17, 0x2e, 0x6d, 0x65, 0x6e,
	0x73, 0x61, 0x6a, 0x65, 0x72, 0x6f, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x63,
	0x69, 0x6f, 0x6e, 0x1a, 0x1d, 0x2e, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x72, 0x6f, 0x2e,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x75, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x63, 0x69,
	0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x06, 0x45, 0x6e, 0x76, 0x69, 0x61, 0x72, 0x12, 0x15, 0x2e, 0x6d,
	0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x72, 0x6f, 0x2e, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65,
	0x41, 0x70, 0x70, 0x1a, 0x13, 0x2e, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x72, 0x6f, 0x2e,
	0x43, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x12, 0x33, 0x0a, 0x07, 0x4f, 0x62, 0x74, 0x65,
	0x6e, 0x65, 0x72, 0x12, 0x10, 0x2e, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x72, 0x6f, 0x2e,
	0x56, 0x61, 0x63, 0x69, 0x6f, 0x1a, 0x16, 0x2e, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x72,
	0x6f, 0x2e, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x73, 0x41, 0x70, 0x70, 0x12, 0x34, 0x0a,
	0x06, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x72, 0x12, 0x10, 0x2e, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a,
	0x65, 0x72, 0x6f, 0x2e, 0x56, 0x61, 0x63, 0x69, 0x6f, 0x1a, 0x18, 0x2e, 0x6d, 0x65, 0x6e, 0x73,
	0x61, 0x6a, 0x65, 0x72, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x55, 0x73, 0x75, 0x61, 0x72,
	0x69, 0x6f, 0x73, 0x12, 0x34, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x6f, 0x6e, 0x65, 0x63, 0x74,
	0x61, 0x72, 0x12, 0x10, 0x2e, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x72, 0x6f, 0x2e, 0x56,
	0x61, 0x63, 0x69, 0x6f, 0x1a, 0x13, 0x2e, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x72, 0x6f,
	0x2e, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x42, 0x0f, 0x5a, 0x0d, 0x6d, 0x65, 0x6e,
	0x73, 0x61, 0x6a, 0x65, 0x72, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pkg_mensajero_proto_rawDescOnce sync.Once
	file_pkg_mensajero_proto_rawDescData = file_pkg_mensajero_proto_rawDesc
)

func file_pkg_mensajero_proto_rawDescGZIP() []byte {
	file_pkg_mensajero_proto_rawDescOnce.Do(func() {
		file_pkg_mensajero_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_mensajero_proto_rawDescData)
	})
	return file_pkg_mensajero_proto_rawDescData
}

var file_pkg_mensajero_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_mensajero_proto_goTypes = []interface{}{
	(*Correcto)(nil),           // 0: mensajero.Correcto
	(*ObtenerConLimite)(nil),   // 1: mensajero.ObtenerConLimite
	(*ListaUsuarios)(nil),      // 2: mensajero.ListaUsuarios
	(*Registracion)(nil),       // 3: mensajero.Registracion
	(*TokenAutenticacion)(nil), // 4: mensajero.TokenAutenticacion
	(*Vacio)(nil),              // 5: mensajero.Vacio
	(*MensajeApp)(nil),         // 6: mensajero.MensajeApp
	(*MensajesApp)(nil),        // 7: mensajero.MensajesApp
}
var file_pkg_mensajero_proto_depIdxs = []int32{
	6, // 0: mensajero.MensajesApp.mensajes:type_name -> mensajero.MensajeApp
	3, // 1: mensajero.Mensajero.Conectar:input_type -> mensajero.Registracion
	6, // 2: mensajero.Mensajero.Enviar:input_type -> mensajero.MensajeApp
	5, // 3: mensajero.Mensajero.Obtener:input_type -> mensajero.Vacio
	5, // 4: mensajero.Mensajero.Listar:input_type -> mensajero.Vacio
	5, // 5: mensajero.Mensajero.Desconectar:input_type -> mensajero.Vacio
	4, // 6: mensajero.Mensajero.Conectar:output_type -> mensajero.TokenAutenticacion
	0, // 7: mensajero.Mensajero.Enviar:output_type -> mensajero.Correcto
	7, // 8: mensajero.Mensajero.Obtener:output_type -> mensajero.MensajesApp
	2, // 9: mensajero.Mensajero.Listar:output_type -> mensajero.ListaUsuarios
	0, // 10: mensajero.Mensajero.Desconectar:output_type -> mensajero.Correcto
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_mensajero_proto_init() }
func file_pkg_mensajero_proto_init() {
	if File_pkg_mensajero_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_mensajero_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Correcto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_mensajero_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObtenerConLimite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_mensajero_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListaUsuarios); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_mensajero_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Registracion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_mensajero_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenAutenticacion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_mensajero_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vacio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_mensajero_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MensajeApp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_mensajero_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MensajesApp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_mensajero_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_mensajero_proto_goTypes,
		DependencyIndexes: file_pkg_mensajero_proto_depIdxs,
		MessageInfos:      file_pkg_mensajero_proto_msgTypes,
	}.Build()
	File_pkg_mensajero_proto = out.File
	file_pkg_mensajero_proto_rawDesc = nil
	file_pkg_mensajero_proto_goTypes = nil
	file_pkg_mensajero_proto_depIdxs = nil
}
